[tool.poetry]
name = "soloviy"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-mpd2 = "^3.1.0"
pyqtconfig = "^0.9.2"
qtinter = "^0.11.0"
pyqt5 = "^5.15.9"
pillow = "^9.5.0"
aiocache = "^0.12.1"
pandas = "^2.0.3"
pyyaml = "^6.0"
xdg = "^6.0.0"
qtrio = "^0.7.0"
attrs = "^23.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
