[logging]
level = "DEBUG"

[mpd]
native_config = "@format {this.xdg_config_dir}/mpd.conf"
native_socket = "@format {this.xdg_data_dir}/mpd.socket"
socket = ""
connection_timeout = 10

[soloviy]
tiling_mode = 4
playlists_margin = 2

[default]
group_by = "directory"
grpc_port = 50051