test_playlist = [
    {
        "file": "Dune/01 - Dream of Arrakis.flac",
        "last-modified": "2024-01-13T18:47:26Z",
        "title": "Dream of Arrakis",
        "artist": "Hans Zimmer",
        "album": "Dune (Original Motion Picture Soundtrack)",
        "date": "2021",
        "genre": "Soundtrack",
        "composer": "Hans Zimmer",
        "track": "1",
        "albumartist": "Hans Zimmer",
        "time": "189",
        "duration": "188.746",
    },
    {
        "file": "Dune/02 - Herald of the Change.flac",
        "last-modified": "2024-01-13T18:47:30Z",
        "title": "Herald of the Change",
        "artist": "Hans Zimmer",
        "album": "Dune (Original Motion Picture Soundtrack)",
        "date": "2021",
        "genre": "Soundtrack",
        "composer": "Hans Zimmer",
        "track": "2",
        "albumartist": "Hans Zimmer",
        "time": "301",
        "duration": "301.013",
    },
    {
        "file": "Dune/03 - Bene Gesserit.flac",
        "last-modified": "2024-01-13T18:47:27Z",
        "title": "Bene Gesserit",
        "artist": "Hans Zimmer",
        "album": "Dune (Original Motion Picture Soundtrack)",
        "date": "2021",
        "genre": "Soundtrack",
        "composer": "Hans Zimmer",
        "track": "3",
        "albumartist": "Hans Zimmer",
        "time": "234",
        "duration": "234.480",
    },
    {
        "file": "Dune/04 - Gom Jabbar.flac",
        "last-modified": "2024-01-13T18:46:42Z",
        "title": "Gom Jabbar",
        "artist": "Hans Zimmer",
        "album": "Dune (Original Motion Picture Soundtrack)",
        "date": "2021",
        "genre": "Soundtrack",
        "composer": "Hans Zimmer",
        "track": "4",
        "albumartist": "Hans Zimmer",
        "time": "120",
        "duration": "120.466",
    },
    {
        "file": "Dune/05 - The One.flac",
        "last-modified": "2024-01-13T18:47:33Z",
        "title": "The One",
        "artist": "Hans Zimmer",
        "album": "Dune (Original Motion Picture Soundtrack)",
        "date": "2021",
        "genre": "Soundtrack",
        "composer": "Hans Zimmer",
        "track": "5",
        "albumartist": "Hans Zimmer",
        "time": "151",
        "duration": "150.613",
    },
    {
        "file": "Dune/06 - Leaving Caladan.flac",
        "last-modified": "2024-01-13T18:47:31Z",
        "title": "Leaving Caladan",
        "artist": "Hans Zimmer",
        "album": "Dune (Original Motion Picture Soundtrack)",
        "date": "2021",
        "genre": "Soundtrack",
        "composer": "Hans Zimmer",
        "track": "6",
        "albumartist": "Hans Zimmer",
        "time": "115",
        "duration": "115.120",
    },
]
