# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x0b\x62\x61\x63kend.api\x1a\x1bgoogle/protobuf/empty.proto\"\x15\n\x04UUID\x12\r\n\x05value\x18\x01 \x01(\x0c\"7\n\x0cListMetaTile\x12\'\n\x08metatile\x18\x01 \x03(\x0b\x32\x15.backend.api.MetaTile\"\x1c\n\x0cPlaylistName\x12\x0c\n\x04name\x18\x01 \x01(\t\";\n\x0cListPlaylist\x12+\n\x08playlist\x18\x01 \x03(\x0b\x32\x19.backend.api.PlaylistName\"\x1d\n\rPlaylistGroup\x12\x0c\n\x04name\x18\x01 \x01(\t\"T\n\x08MetaTile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06locked\x18\x02 \x01(\x08\x12\x14\n\x0corder_by_col\x18\x03 \x01(\t\x12\x14\n\x0corder_by_asc\x18\x04 \x01(\t2\xfa\x01\n\tTilingAPI\x12=\n\x08GetTiles\x12\x16.google.protobuf.Empty\x1a\x19.backend.api.ListMetaTile\x12;\n\x07\x41\x64\x64Tile\x12\x19.backend.api.PlaylistName\x1a\x15.backend.api.MetaTile\x12\x38\n\x07\x44\x65lTile\x12\x15.backend.api.MetaTile\x1a\x16.google.protobuf.Empty\x12\x37\n\x07UpdTile\x12\x15.backend.api.MetaTile\x1a\x15.backend.api.MetaTile2\x95\x01\n\x06MpdAPI\x12\x44\n\x0eGetActiveGroup\x12\x16.google.protobuf.Empty\x1a\x1a.backend.api.PlaylistGroup\x12\x45\n\x0cGetPlaylists\x12\x1a.backend.api.PlaylistGroup\x1a\x19.backend.api.ListPlaylistb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UUID']._serialized_start=55
  _globals['_UUID']._serialized_end=76
  _globals['_LISTMETATILE']._serialized_start=78
  _globals['_LISTMETATILE']._serialized_end=133
  _globals['_PLAYLISTNAME']._serialized_start=135
  _globals['_PLAYLISTNAME']._serialized_end=163
  _globals['_LISTPLAYLIST']._serialized_start=165
  _globals['_LISTPLAYLIST']._serialized_end=224
  _globals['_PLAYLISTGROUP']._serialized_start=226
  _globals['_PLAYLISTGROUP']._serialized_end=255
  _globals['_METATILE']._serialized_start=257
  _globals['_METATILE']._serialized_end=341
  _globals['_TILINGAPI']._serialized_start=344
  _globals['_TILINGAPI']._serialized_end=594
  _globals['_MPDAPI']._serialized_start=597
  _globals['_MPDAPI']._serialized_end=746
# @@protoc_insertion_point(module_scope)
